apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoapp.fullname" . }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
